# Generated by Django 2.1 on 2018-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Digite seu nome', max_length=100, null=True, verbose_name='Nome')),
                ('cpf', models.IntegerField(blank=True, help_text='Digite seu CPF', null=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, help_text='Digite seu e-mail', max_length=60, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, help_text='Digite seu endereço', max_length=100, null=True, verbose_name='Endereço')),
                ('telefone', models.IntegerField(blank=True, help_text='Digite seu telefone', null=True, verbose_name='Nº telefone celular')),
                ('idade', models.IntegerField(blank=True, help_text='Digite sua idade', null=True, verbose_name='Idade')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('musica', models.CharField(max_length=100, verbose_name='Nome da Música')),
                ('compositor', models.CharField(max_length=100, verbose_name='Compositor')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
        ),
    ]
